language: node_js
node_js:
- node
env:
  global:
  - NODE_ENV=ci
services:
- redis-server
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - staging
  - develop
install:
- npm install
script:
- npm test

before_deploy:
- openssl aes-256-cbc -K $encrypted_97069491716d_key -iv $encrypted_97069491716d_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: bash scripts/deploy.bash
  on:
    branch: master